const el1 =document.querySelector("table#age-table")
console.log(el1)
const els2=document.querySelectorAll("table label")
console.log(els2)
const el3=document.querySelector("table td:first-child")
console.log(el3)
const el4=document.querySelector("form[name=search]")
console.log(el4)
const el5=document.querySelectorAll("form label:first-child input:first-child")
console.log(el5)
const el6=document.querySelectorAll("form > input:last-child")
console.log(el6)
